name: Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  BuildARMWheels:
    runs-on: ubuntu-latest
    name: Build on ubuntu-20.04 armv7
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.7
        name: Build wheels within Docker container
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/pymedphys"
          install: |
            apt-get update -q -y
            apt-get install python3 curl -q -y
            apt-get install ca-certificates -q y
          run: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
            cd /pymedphys
            poetry install -E wheels
            poetry run pymedphys dev wheels

      - uses: actions/upload-artifact@v2
        with:
          name: ARM-wheels
          path: wheels
